[project]
name = "mediawikirag"
version = "0.1.0"
description = "A Python project managed with uv."
authors = ["Your Name <your.email@example.com>"]
readme = "README.md"
requires-python = ">=3.8"

[tool.uv]

[tool.uv.extra-build-dependencies]
mediawikirag = ["uv.build"]

[build-system]
requires = ["uv", "uv.build"]
build-backend = "uv.build"
